POST http://localhost:8080/api/user/create
Content-Type: application/json

{ "username":"ahmed",
"password": "abcdefgh",
"confirmPassword": "abcdefgh"
}

###

GET http://localhost:8080/api/user/khalil

###

POST http://localhost:8080/api/cart/addToCart
Content-Type: application/json

{"username":"khalil", "itemId": 1, "quantity": 1}

###

POST http://localhost:8080/api/order/submit/khalil

###

GET http://localhost:8080/api/order/history/khalil

###

GET http://localhost:8080/api/item/1

###
GET http://localhost:8080/api/item/name/Round Widget
